services:
  - type: worker
    name: tiktok-trending-bot
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      playwright install
    startCommand: python tiktok_bot_gmv_excel.py
